CREATE TABLE movements_cards (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    card_id BIGINT NOT NULL,
    from_column_id BIGINT,
    to_column_id BIGINT NOT NULL,
    moved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_card FOREIGN KEY (card_id) REFERENCES CARDS(id) ON DELETE CASCADE,
    CONSTRAINT fk_from_column FOREIGN KEY (from_column_id) REFERENCES BOARDS_COLUMNS(id) ON DELETE SET NULL,
    CONSTRAINT fk_to_column FOREIGN KEY (to_column_id) REFERENCES BOARDS_COLUMNS(id) ON DELETE CASCADE
) ENGINE=InnoDB;