/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.sql.SQLException;

import static org.example.persistence.config.ConnectionConfig.getConnection;
import org.example.persistence.migration.MigrationStrategy;
import org.example.ui.MainMenu;



public class Main {

    public static void main(String[] args) throws SQLException {
        try(var connection = getConnection()){
            new MigrationStrategy(connection).executeMigration();
        }
        new MainMenu().execute();
    }



}
